### ISSUE TITLE
New player doesnt receive bitcoin address

### ISSUE THREAD

**Issue by dragonhuntr** [jordigoyanes/BitBlocks#1]
Happens when someone joins

[04:31:04 ERROR]: Could not pass event PlayerJoinEvent to scriptcraft v3.2.1-2017-09-23
jdk.nashorn.internal.runtime.ECMAException: SyntaxError: Invalid JSON: <json>:1:0 Expected json literal but found u
undefined
^
        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[nashorn.jar:?]
        at jdk.nashorn.internal.runtime.ECMAErrors.syntaxError(ECMAErrors.java:160) ~[nashorn.jar:?]
        at jdk.nashorn.internal.runtime.ECMAErrors.syntaxError(ECMAErrors.java:145) ~[nashorn.jar:?]
        at jdk.nashorn.internal.runtime.JSONFunctions.parse(JSONFunctions.java:81) ~[nashorn.jar:?]
        at jdk.nashorn.internal.objects.NativeJSON.parse(NativeJSON.java:119) ~[nashorn.jar:?]
        at jdk.nashorn.internal.scripts.Script$Recompilation$281$3549A$\^eval\_.L:1#updateBalance(<eval>:110) ~[?:?]
        at jdk.nashorn.internal.scripts.Script$Recompilation$280$636AA$\^eval\_.L:1#playerJoin(<eval>:37) ~[?:?]
        at jdk.nashorn.internal.scripts.Script$Recompilation$64$1377AA$\^eval\_.L:1#on#execute(<eval>:61) ~[?:?]
        at org.bukkit.plugin.EventExecutor$$NashornJavaAdapter.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: jdk.nashorn.internal.runtime.ParserException: <json>:1:0 Expected json literal but found u
undefined
^
        at jdk.nashorn.internal.parser.JSONParser.error(JSONParser.java:529) ~[nashorn.jar:?]
        at jdk.nashorn.internal.parser.JSONParser.error(JSONParser.java:533) ~[nashorn.jar:?]
        at jdk.nashorn.internal.parser.JSONParser.expectedError(JSONParser.java:541) ~[nashorn.jar:?]
        at jdk.nashorn.internal.parser.JSONParser.parseLiteral(JSONParser.java:182) ~[nashorn.jar:?]
        at jdk.nashorn.internal.parser.JSONParser.parse(JSONParser.java:148) ~[nashorn.jar:?]
        at jdk.nashorn.internal.runtime.JSONFunctions.parse(JSONFunctions.java:79) ~[nashorn.jar:?]
        ... 19 more

**Comment by dragonhuntr** [comment]
oh my! when someone doesnt have their address and types /bithelp, this is what happens

[04:37:38 ERROR]: [scriptcraft] Error while trying to execute command: ["bithelp"]
[04:37:38 ERROR]: [scriptcraft] javax.script.ScriptException: TypeError: Cannot read property "BTCaddress" from undefined in <eval> at line number 36 at column number 6
[04:37:38 WARN]: javax.script.ScriptException: TypeError: Cannot read property "BTCaddress" from undefined in <eval> at line number 36 at column number 6
[04:37:38 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
[04:37:38 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
[04:37:38 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
[04:37:38 WARN]:        at org.scriptcraftjs.bukkit.ScriptCraftPlugin.onCommand(ScriptCraftPlugin.java:76)
[04:37:38 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[04:37:38 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[04:37:38 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641)
[04:37:38 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)
[04:37:38 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)
[04:37:38 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[04:37:38 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[04:37:38 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[04:37:38 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[04:37:38 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[04:37:38 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[04:37:38 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[04:37:38 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[04:37:38 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[04:37:38 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[04:37:38 WARN]:        at java.lang.Thread.run(Thread.java:745)
[04:37:38 WARN]: Caused by: <eval>:36:6 TypeError: Cannot read property "BTCaddress" from undefined
[04:37:38 WARN]:        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
[04:37:38 WARN]:        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
[04:37:38 WARN]:        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
[04:37:38 WARN]:        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
[04:37:38 WARN]:        at jdk.nashorn.internal.runtime.Undefined.get(Undefined.java:157)
[04:37:38 WARN]:        at jdk.nashorn.internal.scripts.Script$Recompilation$289$5755AA$\^eval\_.L:1#L:157(<eval>:158)
[04:37:38 WARN]:        at jdk.nashorn.internal.scripts.Script$Recompilation$288$274AA$\^eval\_.L:1#executeCmd(<eval>:33)

**Comment by dragonhuntr** [comment]
On my first account, it gave me an address when i join, but when i join on my alt, thats what happens
(no address)

**Comment by jordigoyanes** [comment]
Bug fixed.
